[project]
name = "Telesto"
version = "0.1.0"
description = "Agentic Framework to build a Oil Prediction model using knowledge base."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling",
    "docling-core",
    "pdfplumber>=0.11.7",
    "pypdf>=6.0.0",
    "pypdf2>=3.0.1",
    "tesserocr>=2.8.0",
    "sqlalchemy",
    "psycopg2-binary",
    "numpy",
    "pgvector",
]
